#!/usr/bin/env node
// Rasterize local carousel HTML. Uses an installed Playwright + Chrome, never uploads.
const fs=require('node:fs');const path=require('node:path');const {pathToFileURL}=require('node:url');
(async()=>{let chromium;try{({chromium}=require('playwright'))}catch(e){throw Error('Playwright is required. Install it in a local tool directory and set NODE_PATH to its node_modules. See references/share-series.md.');}
const directory=path.resolve(process.argv[2]||'');if(!process.argv[2])throw Error('Usage: node export_share.cjs <share-directory>');const manifestPath=path.join(directory,'manifest.json');const manifest=JSON.parse(fs.readFileSync(manifestPath,'utf8'));const browser=await chromium.launch({channel:process.env.PULSEBEAT_BROWSER_CHANNEL||'chrome',headless:true});
try{if(!fs.existsSync(path.join(directory,'cards.html')))fs.copyFileSync(path.join(directory,'index.html'),path.join(directory,'cards.html'));const page=await browser.newPage({viewport:{width:1080,height:1440},deviceScaleFactor:1});await page.route(/^https?:/,route=>route.abort());await page.goto(pathToFileURL(path.join(directory,fs.existsSync(path.join(directory,'cards.html'))?'cards.html':'index.html')).href);await page.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.images].map(async i=>{i.loading='eager';await i.decode();}));});const cards=page.locator('.share-card');const count=await cards.count();if(count!==manifest.count)throw Error('Card count mismatch');const files=[];
for(let i=0;i<count;i++){const card=cards.nth(i);const overflow=await card.locator('.content').evaluate(el=>el.scrollHeight>el.clientHeight+1||el.scrollWidth>el.clientWidth+1);if(overflow)throw Error('Content overflows card '+(i+1)+'; shorten the copy before exporting.');const name=String(i+1).padStart(2,'0')+'-pulsebeat.png';await card.screenshot({path:path.join(directory,name),animations:'disabled'});fs.chmodSync(path.join(directory,name),0o600);files.push(name);}
manifest.rendered=true;manifest.files=files;fs.writeFileSync(manifestPath,JSON.stringify(manifest,null,2));require('node:child_process').execFileSync(process.env.PULSEBEAT_PYTHON||'python3',['-c',"import sys,pathlib,json,zipfile,os; p=pathlib.Path(sys.argv[1]); m=json.loads((p/'manifest.json').read_text()); z=zipfile.ZipFile(p/'share-images.zip','w',zipfile.ZIP_DEFLATED); [z.write(p/f,f) for f in m['files']]; z.close(); os.chmod(p/'share-images.zip',0o600)",directory]);require('node:child_process').execFileSync(process.env.PULSEBEAT_PYTHON||'python3',[path.join(__dirname,'share_viewer.py'),directory]);console.log(JSON.stringify({count,dimensions:manifest.size,directory,files}));
}finally{await browser.close();}})().catch(e=>{console.error(e.message);process.exitCode=1});
